---
title: "Project2"
output:
  word_document: default
  html_document: default
date: '2023-03-21'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load the mlbench package which has the BreastCancer data set
install.packages('mlbench')
require(mlbench)
# if you don't have any required package, use the install.packages() command
# load the data set
data(BreastCancer)

mydata <- cbind(BreastCancer[5],BreastCancer[1:4]) 
head(BreastCancer)
#Id Cl.thickness Cell.size Cell.shape Marg.adhesion Epith.c.size
#1 1000025            5         1          1             1            2
#2 1002945            5         4          4             5            7
#3 1015425            3         1          1             1            2
#4 1016277            6         8          8             1            3
#5 1017023            4         1          1             3            2
#6 1017122            8        10         10             8            7
#Bare.nuclei Bl.cromatin Normal.nucleoli Mitoses     Class
#1           1           3               1       1    benign
#2          10           3               2       1    benign
#3           2           3               1       1    benign
#4           4           3               7       1    benign
#5           1           3               1       1    benign
#6          10           9               7       1 malignant
library(e1071)

install.packages("klaR")

library(klaR)
mynb <- NaiveBayes(Class ~ ., BreastCancer)
mynb.pred <- predict(mynb, BreastCancer)
table(mynb.pred$class,BreastCancer$Class)

#benign malignant
#benign       443         2
#malignant     15       239

library(nnet)
mynnet <- nnet(Class ~ ., BreastCancer, size=1)
mynnet.pred <- predict(mynnet,BreastCancer,type="class")
table(mynnet.pred,BreastCancer$Class)

# weights:  712
#initial  value 473.466909 
#iter  10 value 88.200941
#iter  20 value 82.608418
#iter  30 value 78.436176
#iter  40 value 78.203689
#iter  50 value 70.797846
#iter  60 value 65.896378
#iter  70 value 61.456267
#iter  80 value 61.311028
#iter  90 value 61.308693
#iter 100 value 61.306768
#final  value 61.306768 
#stopped after 100 iterations

#mynnet.pred benign malignant
#benign       435         4
#malignant      9       235

#Decision trees
library(rpart)
mytree <- rpart(Class ~ ., BreastCancer)
plot(mytree); text(mytree) # in "iris_tree.ps"
summary(mytree)
mytree.pred <- predict(mytree,BreastCancer,type="class")
table(mytree.pred,BreastCancer$Class)

#mytree.pred benign malignant
#benign       455         1
#malignant      3       240


# mytree <- rpart(Class ~ ., BreastCancer[-i,])
  #mytree.pred <- predict(mytree,BreastCancer[i,],type="class")
  #ans[i] <- mytree.pred


#Regularised Discriminant Analysis
library(klaR)
myrda <- rda(Class ~ ., BreastCancer)
myrda.pred <- predict(myrda, BreastCancer)
table(myrda.pred$class,BreastCancer$Class)


#Random Forests
library(randomForest)
myrf <- randomForest(Class ~ .,BreastCancer)
myrf.pred <- predict(myrf, BreastCancer)
table(myrf.pred, BreastCancer$Class)

combine.df <- c(mynb.pred, mynnet.pred, mytree.pred, myrda.pred)
combine.df

